"""
Report schemas for the FraudShield agent framework.

Defines the data structures produced by the Report Agent and consumed
by the PDF generation service.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class ReportMetadata(BaseModel):
    """Metadata attached to every generated report."""

    report_id: str = Field(
        ...,
        description="Unique identifier for this report.",
    )
    investigation_id: str = Field(
        ...,
        description="Identifier of the investigation this report covers.",
    )
    title: str = Field(
        default="FraudShield Investigation Report",
        description="Report title displayed on the cover page.",
    )
    author: str = Field(
        default="FraudShield AI",
        description="Report author attribution.",
    )
    classification: str = Field(
        default="Confidential",
        description="Document classification level.",
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when the report was generated.",
    )
    version: str = Field(
        default="1.0",
        description="Report version identifier.",
    )
    status: str = Field(
        default="draft",
        description="Report lifecycle status (draft / final / archived).",
    )
    tags: list[str] = Field(
        default_factory=list,
        description="Searchable tags for report categorisation.",
    )


class ReportSection(BaseModel):
    """A single section within the report body."""

    section_id: str = Field(
        ...,
        description="Unique identifier for this section.",
    )
    title: str = Field(
        ...,
        description="Section heading.",
    )
    content: str = Field(
        ...,
        description="Section body text or markdown content.",
    )
    order: int = Field(
        ...,
        description="Display order (ascending).",
    )
    section_type: str = Field(
        default="text",
        description="Section type hint (text, table, chart, summary).",
    )
    subsections: list["ReportSection"] = Field(
        default_factory=list,
        description="Nested sub-sections.",
    )


class ReportContent(BaseModel):
    """Structured content of a generated report.

    Stored in ``AgentState.report`` and passed to the PDF generator.
    """

    metadata: ReportMetadata = Field(
        ...,
        description="Report-level metadata.",
    )
    executive_summary: str = Field(
        default="",
        description="High-level executive summary paragraph.",
    )
    sections: list[ReportSection] = Field(
        default_factory=list,
        description="Ordered list of report sections.",
    )
    provider_tables: list[dict] = Field(
        default_factory=list,
        description="Provider summary tables for the appendices.",
    )
    recommendation_summary: str = Field(
        default="",
        description="Consolidated recommendation summary.",
    )
    disclaimer: str = Field(
        default="This report is generated by AI and should be reviewed by a qualified investigator.",
        description="Legal disclaimer appended to every report.",
    )
    generated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when the content was assembled.",
    )
    output_path: Optional[str] = Field(
        default=None,
        description="Filesystem path where the PDF was written (set after generation).",
    )
